* Introduction
These licenses and projects have stronger restrictions regarding privative
for-profit usage but still give _individuals_ the 4-freedoms of Free Software.

The licenses may restrict by entity type (Anticapitalist License / CoopyLeft) or
have stronger contribution requirements than Aferro GPL. (Parity Public License)

This is not legal advice, just a bunch of pointers/summaries.
* Licenses
** [[https://anticapitalist.software/][Anti-capitalist License]]
** [[https://lynnesbian.space/csl/][Cooperative Software License]]
** [[https://wiki.coopcycle.org/en:license][Coopyleft License]]
** [[https://fair.io/][Fair Source License]]
** [[https://paritylicense.com/][Parity Public License]]
* Projects
** [[https://comrad.app/][Comrad]]
A socialist network: encrypted, insurveillable, unmontizeable, and
self-governing.

- *License*: Anti-capitalist License
- *Stack*: Python

** [[https://gitlab.com/cal-coop/netfarm/netfarm][Netfarm]]
a[n attempt at creating a] replicated object system.

- *License*: Cooperative Software License
- *Stack*: Common Lisp
** [[https://github.com/breadsystems/rtc-care-schedule][RTC Care Schedule]]
Calendar and scheduling system for the Radical Telehealth Collective.

- *License*: Anti-capitalist License
- *Stack*: Clojure
** [[https://togethernet.cargo.site/][Togethernet]]
Open-source communication software designed around the ethos of transparency and
consent.

- *License*: Anti-capitalist License
- *Stack*: Node.js
* Articles
** Freedom isn't Free (Wendy Liu, Logic Mag, 2018)
https://logicmag.io/failure/freedom-isnt-free/
** Post-Open Source (Melody Horn, 2020)
https://www.boringcactus.com/2020/08/13/post-open-source.html
** Software and Anarchy (Gnuxie Lulamoon and Hayley Patton, Cooperative of Applied Language, Draft)
https://gitlab.com/cal-coop/software-anarchy/
** Telekommunist Manifesto, The (Dmytri Kleiner, Institute of Network Cultures, 2010)
http://telekommunisten.net/the-telekommunist-manifesto/
