* Introduction
These licenses and projects have stronger restrictions regarding privative
for-profit usage but still give _individuals_ the 4-freedoms of Free Software.

The licenses may restrict by entity type (Anticapitalist License / CoopyLeft) or
have stronger contribution requirements than Aferro GPL. (Parity Public License)

This is not legal advice, just a bunch of pointers/summaries.
* Licenses
** [[https://anticapitalist.software/][Anti-Capitalist Software License]]
** [[https://lynnesbian.space/csl/][Cooperative Software License]]
** [[https://wiki.coopcycle.org/en:license][Coopyleft License]]
** [[https://fair.io/][Fair Source License]]
** [[https://paritylicense.com/][Parity Public License]]
* Projects

** [[https://github.com/agreements-network/blackstone][Blackstone]]
Smart contracts and high level API powering the Agreements Network.

- *License*: Parity Public License
- *Stack*: Solidity, TypeScript

** [[https://github.com/coopcycle][CoopCycle]]
Logistics & marketplace platform. Only for worker-owned business.

- *License*: Coopyleft License
- *Stack*: JavaScript, PHP

** [[https://github.com/peermaps/eyros][Eyros]]
Multi-dimensional spatial database.

- *License*: Parity Public License
- *Stack*: JavaScript, Rust

** [[https://gitlab.com/cal-coop/netfarm/netfarm][Netfarm]]
a[n attempt at creating a] replicated object system.

- *License*: Cooperative Software License
- *Stack*: Common Lisp

** [[https://github.com/CreativeInquiry/PEmbroider][PEmbroider]]
Embroidery Library for Processing 

- *License*: Anti-Capitalist Software License
- *Stack*: Java, Processing

** [[https://github.com/frewsxcv/rgis][rgis]]
Geospatial data viewer written in Rust. Availble on the web (rgis.app) or natively on desktop.

- *License*: Anti-Capitalist Software License
- *Stack*: Rust

** [[https://github.com/breadsystems/rtc-care-schedule][RTC Care Schedule]]
Calendar and scheduling system for the Radical Telehealth Collective.

- *License*: Anti-Capitalist Software License
- *Stack*: Clojure

** [[https://github.com/FluidNumerics/SELF][Spectral Element Libraries in Fortran (SELF)]]
SELF is an object-oriented Fortran library that support the implementation of Spectral Element Methods for solving partial differential equations.

- *License*: Anti-Capitalist Software License
- *Stack*: Fortran

** [[https://togethernet.cargo.site/][Togethernet]]
Open-source communication software designed around the ethos of transparency and
consent.

- *License*: Anti-Capitalist Software License
- *Stack*: Node.js

* Articles
** Freedom isn't Free (Wendy Liu, Logic Mag, 2018)
https://logicmag.io/failure/freedom-isnt-free/
** Original Sin of Free Software, The (Daniel Goldsmith, 2019)
https://lipu.dgold.eu/original-sin.html
** Post-Open Source (Melody Horn, 2020)
https://www.boringcactus.com/2020/08/13/post-open-source.html
** poverty of "post-open source", The (Gnuxie Lulamoon and Hayley Patton, Cooperative of Applied Language, 2021)
https://applied-langua.ge/posts/the-poverty-of-post-open-source.html
** Software and Anarchy (Gnuxie Lulamoon and Hayley Patton, Cooperative of Applied Language, Draft)
https://gitlab.com/cal-coop/software-anarchy/
** Telekommunist Manifesto, The (Dmytri Kleiner, Institute of Network Cultures, 2010)
http://telekommunisten.net/the-telekommunist-manifesto/
